### ISSUE TITLE
Import doesn't work in python3 (3.5): No module named 'dataset'

### ISSUE THREAD

**Issue by Gmousse** [jbrambleDC/simulacram#10]
Hey,

I want to use simulacrum on python3. I have installed simulacrum correctly by using `pip3`.
But, when I try to `import simulacrum` it raises this error:
````
  File "/usr/local/lib/python3.4/dist-packages/simulacrum/__init__.py", line 8, in <module>
    from .simdata import create
  File "/usr/local/lib/python3.4/dist-packages/simulacrum/simdata.py", line 1, in <module>
    from dataset import DataSet
ImportError: No module named 'dataset'
````
The installation of the dataset module doesn't resolve this issue.

Any idea ?

**Comment by jbrambleDC** [comment]
Hi I have a PR open that fixes this. Once merged, we can cut a new release and you can upgrade with pip.
